// lex.yy.cpp generated by reflex 6.0.0 from hola.l

#define REFLEX_VERSION "6.0.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define REFLEX_OPTION_graphs_file         "sample1.gv"
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               Lexer
#define REFLEX_OPTION_outfile             "lex.yy.cpp"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

class Lexer : public reflex::AbstractLexer<reflex::Matcher> {
 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  Lexer(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual int lex(void);
  // lexer functions accepting new input to scan
  int lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  int lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

int Lexer::lex(void)
{
  static const char *REGEX_INITIAL = "(?m)((?:\\Q*\\E))|((?:\\Q=\\E))|([A-Z_a-z][0-9A-Z_a-z]*)|([0-9]+)|(\"(?:[^\\x0a\"\\x5c]|\\\\[\\x20-\\xff])*\")|([\\x09\\x0a\\x0d\\x20]+)|((?:\\Q//\\E).*)|((?:\\Q/*\\E)(?:[^\\x2a]|\\*+[^\\x2a/])*\\*+(?:\\Q/\\E))";
  static const reflex::Pattern PATTERN_INITIAL(REGEX_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
#line 3 "hola.l"
/* PATTERN */                    /* ACTION */
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
              return int();
            }
            else
            {
              out().put(matcher().input());
            }
            break;
          case 1: // rule hola.l:3: "*" :
#line 3 "hola.l"
return OP_MUL;
            break;
          case 2: // rule hola.l:4: "=" :
#line 4 "hola.l"
return OP_ASSIGN;
            break;
          case 3: // rule hola.l:5: [a-zA-Z_][a-zA-Z0-9_]* :
#line 5 "hola.l"
return ASCII_IDENTIFIER;
            break;
          case 4: // rule hola.l:6: [0-9]+ :
#line 6 "hola.l"
return CONST_NUMBER;
            break;
          case 5: // rule hola.l:7: \"([^\\\"\n]|\\[\x20-\xff])*\" :
#line 7 "hola.l"
return CONST_STRING;
            break;
          case 6: // rule hola.l:8: [ \t\r\n]+ :
#line 8 "hola.l"
/* no action: ignore all white space */
            break;
          case 7: // rule hola.l:9: "//".* :
#line 9 "hola.l"
/* no action: ignore single-line comments */
            break;
          case 8: // rule hola.l:10: "/*"([^*]|\*+[^*/])*\*+"/" :
#line 10 "hola.l"
/* no action: ignore multi-line comments */
            break;
        }
  }
}
